### PR TITLE
Update ember and dependencies

### LINKED ISSUE #13: Deprecated error -  ember-cli-htmlbars upgrade to 1.0.10  is needed
Installed packages for tooling via npm.
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.ini
t.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (C:\Stufessor\slick\node_modules\ember-cli\lib\models\addon.js:896:27)
installing ember-cli-slick

### PR DESCRIPTION
**Pull request by anehx**
fixes #13

### CODE REVIEW

**Comment by denchen** [comment]
Is there any way we can get this merged and a new version rolled out soon? I'd like to get rid of the warnings I'm seeing in my Ember app related to this issue. Thanks!

**Comment by laantorchaweb** [comment]
I'll run some tests and merge this one. Thanks!

**Comment by NickChristensen** [comment]
Any progress on this?

Looks like this old version of `ember-cli-htmlbars` is conflicting with Ember 2.11, because of the move of Ember from bower to npm.

**Comment by laantorchaweb** [comment]
Hey, I'm sorry, I was traveling the whole month, I'm merging this now and try the build on 1.xx versions to see if everything work fine before pushing the new build to npm.

**Comment by ntodd** [comment]
It's now working fine with Ember 2.11 if I reference the merge commit in my dependencies. Any word on getting a new version cut? Thanks a bunch!

**Pull request merged**
